#!/usr/bin/env python3
"""PDF Glossary 한글화 — 영문 표제어에 번역어, 영문 정의에 한글 대역.

원문(quote)은 유지하고 quote_ko 를 병기한다. 대역은 편집 번역이며 원문 인용이 아니다.
"""
from __future__ import annotations

import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import pdf_config as cfg  # noqa: E402

BLEED = re.compile(
    r"(?:\s*\|\s*|\bRisks?\s+\d|\bSection\s+\d|\bHow to cite\b|"
    r"\bTechnical approaches\b|\bCapabilities of\b|\bThis section\b|"
    r"\bGeneral-purpose AI can help\b|\bSome experts believe\b|"
    r"\bRecent advances\b|\(AI\)\s+System\b|\bModel weights, also\b|"
    r"\bPlease refer\b|\bCognitive offloading\b|\bManipulation:\b|"
    r"'General\s*-?\s*purpose AI')",
    re.I,
)

# 영문 표제어 → 한글 표제어 (head에 한글이 없을 때)
HEAD_KO: dict[str, str] = {
    "Sabotage": "사보타주",
    "Deceptive alignment": "기만적 정렬",
    "Pluralistic alignment": "다원적 정렬",
    "Model evaluation": "모델 평가",
    "Interpretability Research": "해석가능성 연구",
    "Adversarial training": "적대적 학습",
    "Insider threats": "내부자 위협",
    "Malware": "악성코드",
    "Cyberattack": "사이버공격",
    "Dual-use science": "이중용도 과학",
    "Toxin": "독소",
    "Zero-day vulnerability": "제로데이 취약점",
    "Multi-agent system": "다중 에이전트 시스템",
    "Autonomous planning": "자율 계획",
    "Fairness": "공정성",
    "Algorithmic Transparency": "알고리즘 투명성",
    "Institutional transparency": "제도적 투명성",
    "Conformity Assessment": "적합성 평가",
    "Systemic risk assessment": "시스템적 위험 평가",
    "Systemic risk tiers": "시스템적 위험 등급",
    "AI lifecycle": "AI 생애주기",
    "Lifecycle Stage": "생애주기 단계",
    "harmonised standard": "조화 표준",
    "Disinformation": "허위조작정보",
    "Synthetic Data": "합성 데이터",
    "Data Provenance": "데이터 출처",
    "Misinformation": "허위정보",
    "Watermark": "워터마크",
    "AI-generated fake content": "AI 생성 가짜 콘텐츠",
    "Training Data": "학습 데이터",
    "Weights": "가중치",
    "Compute": "컴퓨팅",
    "Parameters": "파라미터",
    "Deep Learning": "딥러닝",
    "Model Training": "모델 학습",
    "Inference": "추론",
    "Intellectual property": "지식재산",
    "Personal Data": "개인정보",
    "Privacy": "프라이버시",
    "Bias": "편향",
    "Reliability": "신뢰성",
    "Law Enforcement": "법 집행",
    "Copyright": "저작권",
    "Automation": "자동화",
    "Sensitive data": "민감정보",
    "Data collection": "데이터 수집",
    "Algorithm": "알고리즘",
    "Discrimination": "차별",
    "Digital infrastructure": "디지털 인프라",
    "Narrow AI": "협소 AI",
    "Labour Market": "노동시장",
    "Malfunction": "오작동",
    "Modalities": "모달리티",
    "Persuasion": "설득",
    "AI literacy": "AI 리터러시",
    "Encryption": "암호화",
    "Hacking": "해킹",
    "State-of-the-art": "최신(최고 수준)",
    "Developer": "개발자",
    "LLM": "대규모 언어 모델",
    "Testing Data": "시험 데이터",
}

# 영문 정의 접두 → 한글 대역 (긴 접두 우선 매칭)
# 원문의 핵심 정의문을 옮긴 편집 번역. 잘린·오염된 원문은 정의 부분만 옮긴다.
QUOTE_KO: list[tuple[str, str]] = [
    (
        "An AI's propensity to use its capabilities in line with human intentions or values",
        "인공지능이 인간의 의도나 가치에 맞게 자신의 능력을 쓰는 성향. 맥락에 따라 개발자·운영자·사용자·특정 공동체·사회 전체의 의도·가치를 가리킬 수 있다.",
    ),
    (
        "A form of influence characterised by systematically inducing false beliefs in others",
        "어떤 목표를 위해 타인에게 체계적으로 잘못된 믿음을 심어 주는 형태의 영향력.",
    ),
    (
        "An AI's propensity to use its capabilities in ways that conflict with human intentions, values, or norms",
        "인공지능이 인간의 의도·가치·규범과 어긋나게 능력을 쓰는 성향. 맥락에 따라 개발자·사용자·특정 공동체·사회 전체의 의도·가치를 가리킬 수 있다.",
    ),
    (
        "An AI's propensity to use its capabilities in ways that conflict with human intentions or values",
        "인공지능이 인간의 의도나 가치와 어긋나게 능력을 쓰는 성향. 맥락에 따라 개발자·운영자·사용자·특정 공동체·사회 전체의 의도·가치를 가리킬 수 있다.",
    ),
    (
        "Generating fake content that presents an individual engaging in compromising activities",
        "특정인이 성행위나 약물 사용 등 곤란한 행위에 가담하는 것처럼 보이는 가짜 콘텐츠를 만들어 유포함으로써, 명예·경력을 해치거나 공적 활동에서 물러나게 하려는 행위.",
    ),
    (
        "Inaccurate or misleading information generated by an AI system",
        "인공지능 시스템이 생성하는 부정확하거나 오해를 부르는 정보. 거짓 사실이나 가짜 인용 등이 예다.",
    ),
    (
        "A mismatch between the objective given to an AI and the developer's intention",
        "인공지능에 부여된 목표와 개발자 의도가 어긋나, 의도하지 않거나 바람직하지 않은 행동을 추구하게 되는 상태.",
    ),
    (
        "A failure mode in AI development where the specified objective serves as an imperfect proxy",
        "개발자가 의도한 목표의 불완전한 대리 지표로 목표를 적어 두어, 시스템이 의도치 않은 행동을 하게 되는 개발 실패 유형.",
    ),
    (
        "The tendency of general-purpose AI models and systems to flatter or validate their users",
        "범용 AI 모델·시스템이 사용자를 치켜세우거나 맞장구치는 경향. 그 과정에서 부정확하거나 해로운 정보를 주더라도 그렇게 하는 경우를 포함한다.",
    ),
    (
        "Misalignment that is difficult to detect, because the system behaves in ways that at least initially appear benign",
        "시스템이 적어도 처음에는 무해해 보이는 행동을 하여, 탐지하기 어려운 오정렬.",
    ),
    (
        "An approach to developing AI systems that seeks to represent and balance different, and sometimes conflicting, preferences",
        "서로 다르고 때로 충돌하는 집단의 선호를 반영·균형 맞추려는 AI 시스템 개발 접근.",
    ),
    (
        "Systematic assessments of an AI system's performance, capabilities, vulnerabilities or potential impacts",
        "인공지능 시스템의 성능·능력·취약점·잠재 영향을 체계적으로 평가하는 것. 벤치마크·레드팀·감사 등을 포함하며 배포 전후에 할 수 있다.",
    ),
    (
        "Systematic assessments, before or after deployment, of the performance, capabilities, vulnerability, or potential impacts",
        "배포 전후에 인공지능 모델·시스템의 성능·능력·취약점·잠재 영향을 체계적으로 평가하는 것.",
    ),
    (
        "A systematic process in which dedicated individuals or teams search for vulnerabilities, limitations, or potential for misuse",
        "전담 인력·팀이 다양한 방법으로 취약점·한계·오용 가능성을 찾는 체계적 과정. 흔히 모델·시스템에 바람직하지 않은 행동을 유발하는 입력을 찾아 안전 공백을 드러낸다.",
    ),
    (
        "A protective measure intended to prevent an AI system from causing harm",
        "인공지능 시스템이 해를 끼치지 않도록 막는 보호 조치.",
    ),
    (
        "Built-in safety constraints to ensure that an AI system operates as desired and avoids harmful outcomes",
        "인공지능 시스템이 의도대로 동작하고 해로운 결과를 피하도록 넣는 내장 안전 제약.",
    ),
    (
        "A standardised, often quantitative test or metric used to evaluate and compare the performance of AI systems",
        "실제 사용을 대표하도록 고안된 고정 과제 집합에서 AI 시스템 성능을 평가·비교하는, 표준화되고 대개 정량적인 시험·지표.",
    ),
    (
        "A formal review of an organisation's compliance with standards, policies, and procedures",
        "조직이 표준·정책·절차를 지키는지 공식적으로 검토하는 일. 대개 독립적인 제3자가 수행한다.",
    ),
    (
        "The degree to which humans can understand the inner workings of an AI model, including why it generated a particular output or decision. A model is highly interpretable",
        "인간이 AI 모델의 내부 작동—특정 출력·결정이 나온 이유 포함—을 이해할 수 있는 정도. 수학적 과정을 인간이 추적 가능한 개념으로 옮길 수 있으면 해석가능성이 높다고 본다.",
    ),
    (
        "The degree to which humans can understand the inner workings of an AI model, including why it generated a particular output or decision",
        "인간이 AI 모델의 내부 작동—특정 출력·결정이 나온 이유 포함—을 이해할 수 있는 정도.",
    ),
    (
        "Generating and submitting prompts designed to bypass safeguards and make an AI system produce harmful content",
        "안전장치를 우회해 무기 제조 지침 등 유해 콘텐츠를 내게 하려고 고안한 프롬프트를 만들어 제출하는 행위.",
    ),
    (
        "Generating and submitting prompts designed to bypass guardrails and make an AI system produce harmful content",
        "가드레일을 우회해 무기 제조 지침 등 유해 콘텐츠를 내게 하려고 고안한 프롬프트를 만들어 제출하는 행위.",
    ),
    (
        "The study of how general-purpose AI models function internally, and the development of methods to make this comprehensible to humans",
        "범용 AI 모델의 내부 작동을 연구하고, 이를 인간이 이해할 수 있게 만드는 방법을 개발하는 일.",
    ),
    (
        "Using something, such as an AI system, to intentionally cause harm",
        "인공지능 시스템 등을 써서 의도적으로 해를 끼치는 행위.",
    ),
    (
        "Employing AI to intentionally cause harm",
        "인공지능을 써서 의도적으로 해를 끼치는 행위.",
    ),
    (
        "A machine learning technique used to make models more reliable. First, developers construct inputs that are designed to make a model fail",
        "모델을 더 견고하게 만드는 기계학습 기법. 먼저 모델을 실패시키도록 고안한 입력을 만들고, 이어서 그런 입력을 인식·처리하도록 학습시킨다.",
    ),
    (
        "A machine learning technique used to make models more reliable. First, developers construct 'adversarial inputs'",
        "모델을 더 견고하게 만드는 기계학습 기법. 먼저(예: 레드팀을 통해) 모델을 실패시키도록 고안한 ‘적대적 입력’을 만들고, 이어서 그런 입력을 인식·처리하도록 학습시킨다.",
    ),
    (
        "Harmful software designed to damage, disrupt, or gain unauthorised access to a computer system",
        "컴퓨터 시스템을 손상·방해하거나 무단 접근하도록 만든 유해 소프트웨어. 바이러스·스파이웨어 등 데이터를 훔치거나 해를 끼치는 프로그램을 포함한다.",
    ),
    (
        "A malicious attempt to gain access to a computer system, network or digital device",
        "정보를 훔치거나 파괴하는 등 목적으로 컴퓨터 시스템·네트워크·디지털 기기에 접근하려는 악의적 시도.",
    ),
    (
        "Research and technology that can be applied for beneficial purposes, such as medicine or environmental solutions",
        "의학·환경 해법처럼 이로운 목적에도 쓰일 수 있으나, 생물·화학무기 개발처럼 해를 끼치는 데 오용될 수도 있는 연구·기술.",
    ),
    (
        "Research and technology that can be applied for beneficial purposes, such as in healthcare or energy",
        "의료·에너지처럼 이로운 목적에도 쓰일 수 있으나, 생물·화학무기 개발처럼 해를 끼치는 데 오용될 수도 있는 연구·기술.",
    ),
    (
        "A poisonous substance produced by living organisms",
        "세균·식물·동물 등 생물이 만들거나, 자연 독소를 모방해 합성한 유독 물질. 독성과 노출 수준에 따라 다른 생물에 질병·피해·사망을 일으킬 수 있다.",
    ),
    (
        "An undiscovered or unpatched security flaw in software or hardware",
        "소프트웨어·하드웨어의 미발견·미패치 보안 결함. 공격자가 이미 악용할 수 있어 개발자에게는 고칠 ‘제로(0)일’만 남는다는 뜻에서 이렇게 부른다.",
    ),
    (
        "The range of tasks or functions that an AI system can perform, and how competently it can perform them",
        "인공지능 시스템이 수행할 수 있는 과제·기능의 범위와, 그것을 얼마나 능숙하게 수행하는가.",
    ),
    (
        "The range of tasks that an AI system can perform, and how competently it can perform them",
        "인공지능 시스템이 수행할 수 있는 과제의 범위와, 그것을 얼마나 능숙하게 수행하는가.",
    ),
    (
        "A general-purpose AI which can make plans to achieve goals, adaptively perform tasks involving multiple steps",
        "목표 달성을 위해 계획을 세우고, 여러 단계와 불확실한 결과를 포함하는 과제를 적응적으로 수행하며, 파일 생성·웹 행동·다른 에이전트에 위임 등 환경과 상호작용하는—인간 감독이 거의 없거나 전혀 없는—범용 AI.",
    ),
    (
        "For the purposes of this section, 'agent' usually refers to a biological, chemical, or toxicological substance",
        "이 절에서 ‘agent’는 보통 생물·화학·독성학적 유해 물질을 가리킨다. 아래의 AI 에이전트와 혼동하지 않도록 한다.",
    ),
    (
        "A term sometimes used to refer to particularly capable AI that matches or exceeds the",
        "오늘날 가장 앞선 AI의 맞먹거나 넘는 특히 능력 있는 AI를 가리키는 말로 쓰이기도 한다. 이 보고서에서는 특히 능력 있는 범용 AI로 이해할 수 있다.",
    ),
    (
        "A scenario in which one or more general-purpose AI systems come to operate outside of anyone's control",
        "하나 이상의 범용 AI 시스템이 누구의 통제도 받지 않고 동작하며, 통제를 되찾을 명확한 경로가 없는 시나리오.",
    ),
    (
        "A network of interacting (AI) agents that may adapt to each other's behaviour and goals",
        "서로의 행동·목표에 적응하며—협력하거나 경쟁할 수도 있는—(AI) 에이전트들의 상호작용 네트워크.",
    ),
    (
        "An AI system's ability to develop and execute multi-step strategies with little or no human guidance",
        "인간 안내가 거의 없거나 전혀 없이도 다단계 전략을 세우고 실행하는 인공지능 시스템의 능력.",
    ),
    (
        "A societal value according to which AI systems should make decisions that are free from bias or unjust discrimination",
        "인공지능 시스템이 편향이나 부당한 차별 없이, 특히 인종·성별·연령·사회경제적 지위 등 보호 속성과 관련해 모든 개인·집단을 공정하게 대우해야 한다는 사회적 가치.",
    ),
    (
        "The degree to which the factors informing general-purpose AI output",
        "범용 AI의 출력(추천·결정 등)을 좌우하는 요인을 이해관계자가 알 수 있는 정도. 모델 내부 작동, 학습 방식·데이터, 입력의 어떤 특징이 출력에 영향을 줬는지, 다른 상황에서 어떤 결정을 내렸을지 등이 포함될 수 있다.",
    ),
    (
        "The degree to which AI companies disclose technical or organisational information to public or governmental scrutiny",
        "AI 기업이 학습 데이터·모델 구조·배출 데이터·안전·보안 조치·의사결정 과정 등 기술·조직 정보를 공개·정부 감시에 드러내는 정도.",
    ),
    (
        "The degree to which organisations publicly disclose information, such as (in the case of AI developers)",
        "조직이 정보를 공개하는 정도. AI 개발자의 경우 학습 데이터·모델 구조·안전·보안 조치·의사결정 과정 공유 등이 해당한다.",
    ),
    (
        "The field of computer science focused on creating systems or machines capable of performing tasks that typically require human intelligence",
        "학습·추론·문제 해결·자연어 처리·의사결정처럼 보통 인간 지능이 필요한 과제를 수행하는 시스템·기계를 만드는 데 초점을 둔 컴퓨터과학 분야.",
    ),
    (
        "AI that can create new content such as text, images, or audio by learning patterns from existing data",
        "기존 데이터에서 패턴을 학습해 텍스트·이미지·오디오 등 새로운 콘텐츠를 만들어 내는 AI.",
    ),
    (
        "AI systems designed to perform a wide range of tasks across various domains, rather than being specialised for one specific function",
        "한 가지 기능에 특화되지 않고 여러 영역에 걸쳐 폭넓은 과제를 수행하도록 설계된 AI 시스템. 대조: 협소 AI.",
    ),
    (
        "Risks that arise from how AI development and deployment changes human behaviour, organisational practices, or societal structures",
        "AI의 능력 자체보다, 개발·배포가 인간 행동·조직 관행·사회 구조를 바꾸는 데서 생기는 위험. (EU AI법의 ‘시스템적 위험’—고영향 범용 AI 모델의 고영향 능력에 특유한 위험—과는 다른 쓰임에 유의.)",
    ),
    (
        "Broader societal risks associated with general-purpose AI development and deployment, beyond the",
        "개별 모델·시스템의 능력을 넘어, 범용 AI 개발·배포와 관련된 더 넓은 사회적 위험. 노동시장 영향·프라이버시 침해·환경 피해 등이 예다. (EU AI법의 ‘시스템적 위험’ 정의와는 다를 수 있다.)",
    ),
    (
        "The systematic process of identifying, evaluating, mitigating and monitoring risks",
        "위험을 식별·평가·완화·모니터링하는 체계적 과정.",
    ),
    (
        "The distinct stages of developing AI, including data collection and pre-processing, pre-training, fine-tuning",
        "데이터 수집·전처리, 사전학습, 파인튜닝, 모델 통합, 배포, 배포 후 모니터링, 하류 수정 등 AI 개발의 구분된 단계들.",
    ),
    (
        "The level of risk that an individual or organisation is willing to take on",
        "개인이나 조직이 감수할 의향이 있는 위험 수준.",
    ),
    (
        "A quantitative or qualitative limit that distinguishes acceptable from unacceptable risks",
        "허용 가능한 위험과 그렇지 않은 위험을 가르고, 초과 시 특정 위험관리 조치를 촉발하는 정량·정성 한도.",
    ),
    (
        "False or misleading information generated or spread with the intent to deceive or influence people",
        "사람을 속이거나 영향을 주려는 의도로 생성·유포되는 거짓·오도 정보. 대조: 허위정보(Misinformation).",
    ),
    (
        "Data like text or images that has been artificially generated, for instance by general-purpose AI systems",
        "텍스트·이미지처럼 인위적으로—예를 들어 범용 AI로—생성된 데이터. 고품질 자연 데이터가 부족할 때 AI 학습에 쓰이기도 한다.",
    ),
    (
        "Artificially generated data, such as text or images, that is sometimes used to train AI models",
        "텍스트·이미지처럼 인위적으로 생성되어, 다른 출처의 고품질 데이터가 부족할 때 AI 모델 학습에 쓰이기도 하는 데이터.",
    ),
    (
        "A historical record of where data comes from and how it has been processed",
        "데이터가 어디서 왔는지, 어떻게 처리됐는지에 대한 이력 기록.",
    ),
    (
        "A type of AI-generated fake content, consisting of audio or visual content, that misrepresents real people",
        "실제 인물이 하지 않은 말·행동을 한 것처럼 보이게 하는, 오디오·시각 형태의 AI 생성 가짜 콘텐츠.",
    ),
    (
        "A type of AI-generated audio or visual content that depicts people saying or doing things they did not actually say or do",
        "사람들이 실제로 하지 않은 말·행동이나, 일어나지 않은 사건을 묘사하는 AI 생성 오디오·시각 콘텐츠.",
    ),
    (
        "False or misleading information that is generated or spread without intent to deceive",
        "속이려는 의도 없이 생성·유포되는 거짓·오도 정보. 대조: 허위조작정보(Disinformation).",
    ),
    (
        "A subtle, often imperceptible pattern embedded within AI-generated content",
        "AI 생성 콘텐츠(텍스트·이미지·오디오 등)에 심어 인공 출처를 표시하거나 출처를 검증·오용을 탐지하기 위한, 미묘하고 대개 눈에 잘 띄지 않는 패턴.",
    ),
    (
        "Audio, text, or visual content, produced by generative AI, that depicts people or events in a way that differs from reality in a malicious or deceptive way",
        "생성형 AI가 만든 오디오·텍스트·시각 콘텐츠로, 사람들이 하지 않은 일·말하지 않은 말을 보이게 하거나 사건 장소를 바꾸거나 일어나지 않은 일을 그리는 등, 악의적·기만적으로 현실과 다르게 묘사하는 것.",
    ),
    (
        "Model parameters that represent the strength of connection between nodes in a neural network",
        "신경망 노드 간 연결 강도를 나타내는 모델 파라미터. 주어진 입력에 대한 출력을 결정하는 데 중요하며, 성능을 높이도록 학습 과정에서 반복 갱신된다.",
    ),
    (
        "Shorthand for 'computational resources', which refers to the hardware (e.g. graphics processing units (GPUs))",
        "‘컴퓨팅 자원’의 약칭. AI를 학습·실행하는 데 필요한 하드웨어(예: GPU), 소프트웨어(예: 데이터 관리), 인프라(예: 데이터센터)를 가리킨다.",
    ),
    (
        "Shorthand for 'computational resources', which refers to the hardware (e.g. GPUs)",
        "‘컴퓨팅 자원’의 약칭. AI를 학습·실행하는 데 필요한 하드웨어(예: GPU), 소프트웨어(예: 데이터 관리), 인프라(예: 데이터센터)를 가리킨다.",
    ),
    (
        "The numerical components of an AI model, such as weights and biases, that are learned from data during training",
        "학습 중 데이터로부터 배우며 입력을 출력으로 바꾸는 방식을 정하는 AI 모델의 수치 요소(가중치·바이어스 등). 여기서 ‘바이어스’는 차별 맥락의 편향과 무관한 수학 용어다.",
    ),
    (
        "A machine learning technique in which large amounts of data and compute are used to train multilayered, artificial neural networks",
        "대량의 데이터와 컴퓨팅으로 다층 인공신경망(생물 뇌에서 영감)을 학습시켜, 고수준 특징을 자동으로 뽑아내 강력한 패턴 인식·의사결정을 가능하게 하는 기계학습 기법.",
    ),
    (
        "A machine learning technique in which large amounts of compute are used to train multilayered, artificial neural networks",
        "대량의 컴퓨팅으로 다층 인공신경망(생물 뇌에서 영감)을 학습시켜, 대규모 데이터에서 정보를 자동으로 배우게 해 강력한 패턴 인식·의사결정을 가능하게 하는 기계학습 기법.",
    ),
    (
        "A type of AI model consisting of a mathematical structure that is inspired by the human brain",
        "인간 뇌에서 영감을 받은 수학 구조로, 상호 연결된 노드(뉴런에 비유)가 데이터를 처리·학습하는 AI 모델 유형. 현재 범용 AI 시스템의 기반이다.",
    ),
    (
        "A type of AI model composed of interconnected nodes (loosely inspired by biological neurons)",
        "생물 뉴런에서 느슨하게 영감을 받은 상호 연결 노드를 층으로 배치하고, 연결을 조정하며 데이터 패턴을 학습하는 AI 모델 유형. 현재 범용 AI의 기반이다.",
    ),
    (
        "The process in which an AI generates outputs based on a given input, thereby applying the knowledge learnt during training",
        "주어진 입력에 대해 출력을 생성하며, 학습 때 익힌 지식을 적용하는 과정.",
    ),
    (
        "The process of adapting an AI model after its initial training to a specific task",
        "초기 학습 이후 추가 데이터로 특정 과제에 맞추거나 전반적으로 더 유용하게 적응시키는 과정.",
    ),
    (
        "The process of adapting a pre-trained AI model to a specific task",
        "사전학습된 AI 모델을 추가 데이터로 특정 과제에 맞추거나 전반적으로 더 유용하게 적응시키는 과정.",
    ),
    (
        "A general-purpose AI model designed to be adaptable to a wide range of downstream tasks",
        "폭넓은 하류 과제에 적응할 수 있도록 설계된 범용 AI 모델.",
    ),
    (
        "Creations of the mind over which legal rights may be granted",
        "문학·예술 작품, 상징, 명칭, 이미지 등 법적 권리가 부여될 수 있는 정신적 창작물.",
    ),
    (
        "A person's or group's right to control how others access or process their sensitive information and activities",
        "자신이나 집단의 민감 정보·활동에 타인이 접근·처리하는 방식을 스스로 통제할 권리.",
    ),
    (
        "A person's right to control how others access or process data about them",
        "자신에 관한 데이터에 타인이 접근·처리하는 방식을 스스로 통제할 권리.",
    ),
    (
        "Systematic errors in algorithmic systems that favour certain groups or worldviews",
        "특정 집단이나 세계관에 유리하고 일부에게 불공정한 결과를 자주 낳는, 알고리즘 시스템의 체계적 오류. 설계 오류, 비대표·결함 데이터, 기존 사회 불평등 등에서 비롯될 수 있다.",
    ),
    (
        "An AI system's ability to consistently perform its intended function",
        "인공지능 시스템이 의도된 기능을 일관되게 수행하는 능력.",
    ),
    (
        "A form of legal protection granted to creators of original works",
        "원작 창작자에게 부여되는 법적 보호로, 이용·복제·배포에 대한 배타적 권리를 준다.",
    ),
    (
        "The use of technology to perform tasks with reduced or no human involvement",
        "인간 개입을 줄이거나 없이 과제를 수행하도록 기술을 쓰는 것.",
    ),
    (
        "Information that, if disclosed or mishandled, could result in harm, embarrassment, inconvenience, or unfairness",
        "공개되거나 잘못 다루되면 개인·조직에 피해·곤란·불편·불공정을 초래할 수 있는 정보.",
    ),
    (
        "A stage of AI development in which developers and data workers collect, clean, label, standardise, and transform raw training data",
        "개발자와 데이터 작업자가 원시 학습 데이터를 수집·정제·라벨링·표준화·변환하여 모델이 효과적으로 배울 수 있는 형식으로 만드는 AI 개발 단계.",
    ),
    (
        "A set of rules or instructions that enable an AI system to process data and perform specific tasks",
        "인공지능 시스템이 데이터를 처리하고 특정 과제를 수행하게 하는 규칙·지시의 집합.",
    ),
    (
        "The unfair treatment of individuals or groups based on their attributes",
        "인종·성별·연령·종교 등 속성(보호 특성 포함)에 근거한 개인·집단에 대한 불공정한 대우.",
    ),
    (
        "The foundational services and facilities necessary for digital technologies to function",
        "디지털 기술이 작동하는 데 필요한 기반 서비스·시설. 하드웨어·소프트웨어·네트워크·데이터센터·통신 체계 등을 포함한다.",
    ),
    (
        "The foundational services and facilities necessary for computerbased technologies to function",
        "컴퓨터 기반 기술이 작동하는 데 필요한 기반 서비스·시설. 하드웨어·소프트웨어·네트워크·데이터센터·통신 체계 등을 포함한다.",
    ),
    (
        "An AI model or system that is designed to perform only one specific task or a few very similar tasks",
        "웹 검색 결과 순위, 동물 종 분류, 체스처럼 한두 가지 유사 과제만 수행하도록 설계된 AI 모델·시스템. 대조: 범용 AI.",
    ),
    (
        "A kind of AI that is specialised to perform one specific task or a few very similar tasks",
        "웹 검색 결과 순위, 동물 종 분류, 체스처럼 한두 가지 유사 과제에 특화된 AI. 대조: 범용 AI.",
    ),
    (
        "The system in which employers seek to hire workers and workers seek employment",
        "고용주가 노동자를 찾고 노동자가 일자리를 찾는 체계. 일자리 창출·상실, 임금을 아우른다.",
    ),
    (
        "Significant and often complex changes in the labour market that affect job availability",
        "일자리 가용성·필요 숙련·임금 분포·직업의 성격에 영향을 주는, 노동시장의 크고 종종 복잡한 변화.",
    ),
    (
        "The failure of a system to operate as intended by its developer or user",
        "개발자나 사용자가 의도한 대로 동작하지 않아 잘못된·해로운 출력이나 운영 장애를 낳는 시스템의 실패.",
    ),
    (
        "The kinds of data that an AI system can competently receive as input and produce as output, including text",
        "인공지능 시스템이 능숙하게 입력으로 받고 출력으로 낼 수 있는 데이터 종류. 텍스트(언어·코드), 이미지, 영상, 로봇 행동 등을 포함한다.",
    ),
    (
        "The kinds of data that an AI model or system can receive as input and produce as output, such as text",
        "인공지능 모델·시스템이 입력으로 받고 출력으로 낼 수 있는 데이터 종류. 텍스트(언어·코드), 이미지, 영상, 로봇 행동 등.",
    ),
    (
        "A form of influence that uses communication - including rational argument, emotional appeals, or appeals to authority",
        "강제나 강압이 아니라, 합리적 논증·감정적 호소·권위에 대한 호소 등 소통으로 상대의 믿음을 바꾸는 형태의 영향력.",
    ),
    (
        "The process of converting information into a coded format that can only be read by authorised parties",
        "올바른 복호화 키를 가진 인가된 주체만 읽을 수 있도록 정보를 부호화된 형식으로 바꾸는 과정.",
    ),
    (
        "The act of exploiting vulnerabilities or weaknesses in a computer system, network, or software",
        "컴퓨터 시스템·네트워크·소프트웨어의 취약점·약점을 악용해 무단 접근·기능 조작·정보 추출을 하는 행위.",
    ),
    (
        "Any organisation that designs, builds, integrates, adapts or combines AI models or systems",
        "AI 모델·시스템을 설계·구축·통합·적응·결합하는 모든 조직.",
    ),
]


def has_hangul(s: str) -> bool:
    return any("\uac00" <= c <= "\ud7a3" for c in (s or ""))


def clean_en_quote(q: str) -> str:
    q = re.sub(r"\s+", " ", q or "").strip()
    m = BLEED.search(q)
    if m and m.start() > 50:
        q = q[: m.start()].rstrip(" .|;,")
    m2 = re.search(r"\.\s+[A-Z][a-z]+(?:\s+[a-z]+){0,3}:\s+[A-Z]", q)
    if m2 and m2.start() > 60:
        q = q[: m2.start() + 1]
    if len(q) > 480:
        parts = re.split(r"(?<=[.])\s+", q)
        acc: list[str] = []
        n = 0
        for p in parts:
            acc.append(p)
            n += len(p)
            if n > 300:
                break
        q = " ".join(acc)
    return q.strip()


def scrub_for_match(q: str) -> str:
    """파싱 잔여(| 칼럼·옆 항목)를 걷어 접두 매칭이 되게 한다."""
    q = re.sub(r"\s*\|\s*[^|]{0,120}\|\s*", " ", q)
    q = re.sub(r"\s*\|\s*", " ", q)
    q = re.sub(r"\s+", " ", q).strip()
    return q


def is_garbage_quote(q: str) -> bool:
    q = (q or "").strip()
    if has_hangul(q):
        return False  # 한글 원문(고시 인용 등)은 유지
    if len(q) < 30:
        return True
    if "|" in q[:60]:
        return True
    if q.count("|") >= 2 and len(q) < 220:
        return True
    if re.match(r"^(Bias Source|Label Imbalance|Sampling Bias)\b", q):
        return True
    if "exclusive work. administration" in q:
        return True
    if q.lower().startswith("creators of original works, giving them exclusive work"):
        return True
    return False


def translate_quote(en: str) -> str | None:
    if not en or has_hangul(en):
        return None
    if is_garbage_quote(en):
        return None
    cleaned = clean_en_quote(scrub_for_match(en))
    if len(cleaned) < 25:
        return None
    low = cleaned.lower()
    for prefix, ko in sorted(QUOTE_KO, key=lambda x: -len(x[0])):
        if cleaned.startswith(prefix) or low.startswith(prefix.lower()):
            return ko
        if prefix.lower()[:80] in low[:140]:
            return ko
    return None


def localize_head(head: str, en: str) -> str:
    if has_hangul(head):
        return head
    if head in HEAD_KO:
        return HEAD_KO[head]
    for k, v in HEAD_KO.items():
        if k.lower() == head.lower() or k.lower() == (en or "").lower():
            return v
    return head


def main() -> None:
    path = cfg.SITE_JSON
    with open(path, encoding="utf-8") as f:
        data = json.load(f)

    n_head = 0
    n_quote = 0
    n_miss = 0
    n_drop = 0
    for e in data["entries"]:
        old = e["head"]
        e["head"] = localize_head(e["head"], e.get("en") or "")
        if e["head"] != old:
            n_head += 1
            e["head_localized"] = True

        kept = []
        for d in e.get("definitions") or []:
            if is_garbage_quote(d.get("quote") or ""):
                n_drop += 1
                continue
            if has_hangul(d.get("quote") or ""):
                d["quote_ko"] = None
                d.pop("quote_ko_missing", None)
                kept.append(d)
                continue
            ko = translate_quote(d["quote"])
            d["quote_ko"] = ko
            if ko:
                n_quote += 1
                d.pop("quote_ko_missing", None)
            else:
                n_miss += 1
                d["quote_ko_missing"] = True
            kept.append(d)
        e["definitions"] = kept
        e["n_defs"] = len(kept)
        if len(kept) >= 2:
            e["status"] = "multi"
        elif len(kept) == 1:
            e["status"] = "found"
        else:
            e["status"] = "missing"

    data.setdefault("meta", {})["localization"] = {
        "heads_localized": n_head,
        "quotes_translated": n_quote,
        "quotes_untranslated": n_miss,
        "quotes_dropped_garbage": n_drop,
        "note": "quote_ko는 편집 대역이며 PDF 원문 인용이 아님. 원문은 quote에 유지.",
    }
    cov = data["meta"].setdefault("coverage", {})
    cov["found"] = sum(1 for e in data["entries"] if e["status"] in ("found", "multi"))
    cov["multi"] = sum(1 for e in data["entries"] if e["status"] == "multi")
    cov["missing"] = sum(1 for e in data["entries"] if e["status"] == "missing")

    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(
        f"localized heads={n_head} quotes={n_quote} "
        f"untranslated={n_miss} dropped={n_drop} → {path}"
    )


if __name__ == "__main__":
    main()
